
icons:
  placeholderSupport: true

crafts:
  defaults:
    onlyItemStacks: true # Recipe Choices will only trigger by item stack and not material
  disabledCrafts:
    - iron_block

block:
  sounds:
    stepSound:
      enabled: true
    hitSound:
      enabled: true
    fallSound:
      enabled: true

kick-on-decline:
  enabled: true
  bypassPermission: "Mauris.bypassDeclineRP"
  message: "accept the resourcepack please"
  failureMessage: "strange........."

self-host:
  enabled: true
  ip: localhost
  ports:
    - 8090
    - 8091
    - 8092
    - 8093
    - 8094