
icons:
  placeholderSupport: true

block:
  sounds:
    stepSound:
      enabled: true
    hitSound:
      enabled: true
    fallSound:
      enabled: true

kick-on-decline:
  enabled: true
  bypassPermission: "Mauris.bypassDeclineRP"
  message: "accept the resourcepack please"
  failureMessage: "strange........."

self-host:
  enabled: true
  ip: localhost
  port: 8090