
icons:
  placeholderSupport: true


kick-on-decline:
  enabled: true
  bypass-permission: "Mauris.bypassDeclineRP"
  message: "accept the resourcepack please"
  failure-message: "strange........."

self-host:
  enabled: true
  ip: localhost
  port: 8090